#!/bin/bash
function loadwallet() {
echo "Loading wallet"
let COUNTERT=0
OPN=$(transcendence-cli -datadir=/root/.transcendence_$ALIAS getblockchaininfo | wc -l)
while [  $OPN -lt 2 ]; do
sleep 10
OPN=$(transcendence-cli -datadir=/root/.transcendence_$ALIAS getblockchaininfo | wc -l)
COUNTERT=$((COUNTERT+1))
if [ $COUNTERT -gt 3 ]
then
systemctl restart transcendenced$ALIAS
fi
done
echo "Wallet loaded"
}
